### ISSUE TITLE
Shows incorrect hash after checking out outside of VSCode

### ISSUE THREAD

**Issue by basickarl** [Sertion/vscode-gitblame#37]
I checked the hash with the extension. Did a checkout <HASH> +1 (so I revert to the hash BEFORE the hash being displayed) in my terminal outside of VSCode (vscode updates with correct lines of code). This extension does not update the hash though, it displays the old hash.

**Comment by Sertion** [comment]
Hello Karl.

Thank you for the issue.

The GUI only updates when you move the cursor in a document, save a document, or when you swap between files in the editor. Did you do any of these things?

We are also using the vscode built in [`createFileSystemWatcher`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#workspace.createFileSystemWatcher) to detect changes on the file system. What version of vscode are you using and what operating system do you use?

**Comment by Sertion** [comment]
Hello again Karl. I have moved back to using the node [`fs.watch`](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) instead of the build in [`createFileSystemWatcher`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#workspace.createFileSystemWatcher).

Please report back if this resolve the issue!

**Comment by Sertion** [comment]
If this issue ever reappears pleas feel free to create a new issue for it.
