### ISSUE TITLE
Git blame view button in notification allow to open selected range

### ISSUE THREAD

**Issue by aliev** [Sertion/vscode-gitblame#39]
Would be great to show the blame of the selected lines of code. For example when I select lines from 3 to 6 in this file: https://github.com/Sertion/vscode-gitblame/blob/master/src/constants.ts url will be transformed in to: https://github.com/Sertion/vscode-gitblame/blob/master/src/constants.ts#L3-L6 when I click on the "View" button.

Thanks!

**Comment by Sertion** [comment]
Hello Ali!

Thank you for the issue!

Right now if you select more than one line it only blames the line where the cursor is placed (e.g. if you select 3-6 downwards only 6 is blamed).

When selecting multiple lines like this it is possible to run into more than one commit as well. How should those cases be handled?

I do like the idea of sending the user to the last blamed line instead of just blindly to the file they blamed!

You are very welcome to submit a pull request adding this functionality!

// Albin

**Comment by Sertion** [comment]
I have had time to do some more research here and it looks like it it not possible to build something here that would make sense in all online tools. Again it is BitBucket's Mercurial roots that is the exception.

If anyone ever thinks about something here, please create a new issue discussing the possibilities.
