### ISSUE TITLE
why guess url?

### ISSUE THREAD

**Issue by xgdgsc** [Sertion/vscode-gitblame#89]
I noticed you guess url and there are known limitations. Can' t you read from `config` ?

**Comment by Sertion** [comment]
Hey  xgdgsc!

Right now [we guess based on the data we can gather from the git cli on the system as ran from the folder where the tracked file resides](https://github.com/Sertion/vscode-gitblame/blob/35f5f4fe016244fe02c1fefd53075b2910dfb1bc/src/git/util/gitcommand.ts#L79). That is the best way I know how to do it.

The reason the setting is called "guess" is because even when we use the data from the CLI we can't be certain that the user isn't on some very uncommon setup where they git repository origin and the online viewing tool are on completely separate domains.

If there is a configuration option in the git cli for an online viewing tool I would love to add support for it.

**Comment by xgdgsc** [comment]
Why would the opened url is `https` with no port number but the called command like `git config --local --get remote.origin.url ` returns url with correct `http` and port number?

**Comment by Sertion** [comment]
I will look into adding this case.

**Comment by Sertion** [comment]
A new version was just uploaded to the marketplace. It supports keeping the port for http and https origins as well as keeping the protocol as long as it is http or https.

Please comment here if it isn't working as expected.
